const reviewData = {
  reviews: [
    {
      id: 1,
      name: "Aarav",
      rating: 5,
      story: "Spicy enough to wake you up. Perfect post-workout fuel.",
      moment: "🏋️ Gym snack",
      mood: ["Spicy", "Healthy"],
      createdAt: "2026-01-08",
      helpful: 12,
    },
    {
      id: 2,
      name: "Meera",
      rating: 4,
      story: "Paratha + this peanut butter = magic.",
      moment: "🍞 Sunday breakfast",
      mood: ["Crunchy"],
      createdAt: "2025-12-29",
      helpful: 7,
    },
    {
      id: 3,
      name: "Rohit",
      rating: 5,
      story: "Guilt-free and addictive. Dangerous combo.",
      moment: "🌙 Midnight craving",
      mood: ["Spicy"],
      createdAt: "2025-10-01",
      helpful: 18,
    },
    {
      id: 4,
      name: "Ananya",
      rating: 3,
      story: "Good taste, but a little intense for kids.",
      moment: "👨‍👩‍👧 Family snack",
      mood: ["Moderate"],
      createdAt: "2025-07-12",
      helpful: 4,
    },
    {
      id: 5,
      name: "Kunal",
      rating: 2,
      story: "Too spicy for me personally.",
      moment: "🥄 Trial bite",
      mood: ["Spicy"],
      createdAt: "2025-01-18",
      helpful: 2,
    },
    {
      id: 6,
      name: "Pooja",
      rating: 5,
      story: "Finally a peanut butter that isn’t boring.",
      moment: "🥪 Office lunch",
      mood: ["Spicy", "Fun"],
      createdAt: "2026-01-05",
      helpful: 9,
    },
    {
      id: 7,
      name: "Siddharth",
      rating: 4,
      story: "Great kick of spice, goes well with toast.",
      moment: "☀️ Morning bite",
      mood: ["Spicy", "Crunchy"],
      createdAt: "2025-12-10",
      helpful: 6,
    },
    {
      id: 8,
      name: "Neha",
      rating: 5,
      story: "Obsessed. I eat it straight from the jar.",
      moment: "😋 Cheat snack",
      mood: ["Addictive"],
      createdAt: "2025-11-22",
      helpful: 15,
    },
    {
      id: 9,
      name: "Vikram",
      rating: 4,
      story: "Perfect with apples. Didn’t expect that.",
      moment: "🍎 Evening snack",
      mood: ["Balanced"],
      createdAt: "2025-10-15",
      helpful: 5,
    },
    {
      id: 10,
      name: "Isha",
      rating: 3,
      story: "Nice flavor but spice builds up slowly.",
      moment: "🧪 First try",
      mood: ["Moderate"],
      createdAt: "2025-09-03",
      helpful: 3,
    },
    {
      id: 11,
      name: "Arjun",
      rating: 5,
      story: "Protein + spice = dream combo.",
      moment: "🏃 Post-run snack",
      mood: ["Healthy", "Spicy"],
      createdAt: "2025-08-19",
      helpful: 11,
    },
    {
      id: 12,
      name: "Riya",
      rating: 4,
      story: "Loved it, but wouldn’t recommend for spice beginners.",
      moment: "🔥 Bold choice",
      mood: ["Spicy"],
      createdAt: "2025-06-30",
      helpful: 8,
    },
    {
      id: 13,
      name: "Manav",
      rating: 5,
      story: "Way better than regular peanut butter.",
      moment: "🥞 Pancake topping",
      mood: ["Crunchy", "Spicy"],
      createdAt: "2025-05-14",
      helpful: 10,
    },
    {
      id: 14,
      name: "Sneha",
      rating: 3,
      story: "Good quality, just not my taste.",
      moment: "🤔 Honest try",
      mood: ["Mild"],
      createdAt: "2025-03-27",
      helpful: 4,
    },
    {
      id: 15,
      name: "Aditya",
      rating: 4,
      story: "Unexpectedly addictive with crackers.",
      moment: "🧀 Snack plate",
      mood: ["Savory"],
      createdAt: "2025-02-09",
      helpful: 6,
    },
  ],
};

export default reviewData;
